{% set name = "napari-organoid-counter" %}
{% set version = "0.2.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 968a51ca1d9968949cc6e071d0bf3a10a15969250873774924dd86424f6986ea

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8,<3.11
    - setuptools-scm
  run:
    - napari >=0.4.17
    - napari-aicsimageio >=0.7.2
    - numpy
    - python >=3.8,<3.11
    - pytorch >=1.13.1
    - scikit-image
    - torchvision >=0.14.1
    - qtpy

test:
  imports:
    - napari_organoid_counter
  commands:
    - pip list
    # - pip check  # Fails due to aicsimageio deps and fixed constraints that were relaxed
  requires:
    - pip
    - pyqt

about:
  home: https://pypi.org/project/napari-organoid-counter
  summary: A plugin to automatically count lung organoids
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/HelmholtzAI-Consultants-Munich/napari-organoid-counter

extra:
  recipe-maintainers:
    - christinab12
    - goanpeca
    - jaimergp
