{% set name = "napari-organoid-counter" %}
{% set version = "0.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/napari-organoid-counter-{{ version }}.tar.gz
  sha256: fb9ebe7a0d3b9bff7face564fcef28fdd2b6466e288818ddcda59161f973dbdd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools-scm
  run:
    - napari >=0.4.17
    - napari-aicsimageio >=0.7.2
    - numpy
    - python >={{ python_min }},<3.11
    - pytorch >=1.13.1
    - scikit-image
    - torchvision >=0.14.1
    - qtpy

test:
  imports:
    - napari_organoid_counter
  commands:
    - pip list
    # - pip check  # Fails due to aicsimageio deps and fixed constraints that were relaxed
  requires:
    - pip
    - pyqt
    - python {{ python_min }}

about:
  home: https://pypi.org/project/napari-organoid-counter
  summary: A plugin to automatically count lung organoids
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/HelmholtzAI-Consultants-Munich/napari-organoid-counter

extra:
  recipe-maintainers:
    - christinab12
    - goanpeca
    - jaimergp
